### ISSUE TITLE
Unable to validate IFSC code IDIB000C040

### ISSUE THREAD

**Issue by bhatkumble** [razorpay/ifsc#172]
The IFSC code **IDIB000C040** is a valid one and is being shown as invalid when the `validate` function is used

[Here](https://ifsc.bankifsccode.com/IDIB000C040) is the branch info for IFSC code 

Can this be looked into at priority? We have a few bank details to process

**Comment by captn3m0** [comment]
Fixed in upcoming 1.5.1 release.

**Comment by bhatkumble** [comment]
I have verified this in the latest 1.5.1 release. But the issue still persists. The data exists in the datset, but the `ifsc.validate` returns `false`

**Comment by captn3m0** [comment]
@bhatkumble The API version is still 1.5.0, it should be deployed soon. I'll confirm back here once that is done.

**Comment by captn3m0** [comment]
The new version is deployed. If you're on node, please update to `1.5.1-1`
